[#3538] Fix converting substitution to `Map`
runtimeverification/haskell-backend pull request #3553
Opened 2023-03-21 10:29 UTC by alexd1971

Problem: Kore-exec fails with "Cannot convert a denormalized substitution to a map!".

Solution: When appending one condition to another we can get condition with denormalized substitution which leads to the error. Therefore if we get condition with denormalized substitution we need to simplify this condition before converting substitution to `Map`.

Fixes #3538

2023-03-21 20:44 UTC, alexd1971 commented
Performance test results: [report-master_alexe--o-map.pdf](https://github.com/runtimeverification/haskell-backend/files/11033475/report-master_alexe--o-map.pdf)

2023-03-22 10:33 UTC, ana-pantilie requested changes

2023-03-22 10:33 UTC, ana-pantilie commented on kore/src/Kore/Internal/Substitution.hs
> +    Substitution (..),
Please don't export the constructors, they're not exported on purpose.

I'd suggest implementing the logic you need in a separate function in this module, and export that to be used in the desired place.

2023-03-22 13:08 UTC, ana-pantilie approved these changes

2023-03-22 13:08 UTC, merged